name: GraalVM Native Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1.2.2
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      #Build Image
      - name: GraalVM build
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
          native-image --version
          mvn -Pnative spring-boot:build-image

      # Tag the built image
      - name: Tag Image
        run: docker tag native-demo:0.0.1-SNAPSHOT nobasil/native-demo:${{ github.sha }}

      - name: Push Images to Docker Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push nobasil/native-demo:${{ github.sha }}