name: Native-AMD64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: LiveNathan
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true
      #Build Image
      - name: Build Image
        run: ./mvnw -Pnative spring-boot:build-image
      #Deploy the image to the Docker registry
      - name: Push Images to Docker Registry
        run: docker push -a nobasil/native-demo


  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: nobasil
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: pull-arm64
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 6
          command: docker pull nobasil/native-demo:$GITHUB_REF_NAME-aarch_64
      - name: create-manifest
        run: |
          docker manifest create nobasil/native-demo:$GITHUB_REF_NAME --amend nobasil/native-demo:$GITHUB_REF_NAME-x86_64 --amend nobasil/native-demo:$GITHUB_REF_NAME-aarch_64
          docker manifest push nobasil/native-demo:$GITHUB_REF_NAME
          docker manifest create nobasil/native-demo:latest --amend nobasil/native-demo:$GITHUB_REF_NAME-x86_64 --amend nobasil/native-demo:$GITHUB_REF_NAME-aarch_64
          docker manifest push nobasil/native-demo:latest